<?php

// Builds the Zero file for download and usage

/**
error_reporting(E_ALL);
ini_set("display_errors", 1);
/**/

/* Add a / to the end of this line to enable download */
header("Cache-Control: public"); // needed for internet explorer
header("Content-Type: application/text");
header("Content-Disposition: attachment; filename=index.php");
/**/

$content = "";

// Add the PHP tag and version information
$version_info = json_decode(file_get_contents("../version.json"), true);
$content = <<<PHP

<?php

/* * * * * * * * * * * * * * * * * *
 * WARNING: Do NOT Edit This File! *
 * * * * * * * * * * * * * * * * * */

/*
 * Copyright Brandon Dyer
 * All rights reserved
 */

\$zero_version = "${version_info["code"]}";
\$zero_version_number = ${version_info["number"]};
\$content = "";
\$content_api = array();
\$js_to_include = [];
\$js_to_include_first = [];
\$css_to_include = [];
\$cards = [];

if (isset(\$_GET['debug'])) {
  ini_set('display_errors', 1);
  ini_set('display_startup_errors', 1);
  error_reporting(E_ALL);
}

if (count(get_included_files()) == 1) {
  \$is_zero_included = false;
} else {
  \$is_zero_included = true;
}

PHP;

// Function for loading files into the code
function load($file)
{
    global $content;
    if (file_exists("core/" . $file . ".txt")) {
        $text = file_get_contents("core/" . $file . ".txt");
        $text = preg_replace('/^\\<\\?php/', '', $text);
        $text = trim($text, "\r\n");
        $content .= <<<PHP
      if (isset(\$_GET['debug'])) {
         echo "$file<br>\\n";
      }
PHP;
        $content .= "\n// % $file\n" . $text . "\n";
    } else {
        $content .= "\n// Couln't find dependency: $file\n";
    }
}


// Set up the required directories for configuration
load("directories");
// Load the necesary configuration files
load("config");
// Functions required for logging and error reporting
load("logger");
// Updates the index and config files
load("updater");
// Functions for connecting to the database
load("db");
// General helper functions
load("helper_functions");
// Load plugins
load("plugins");
// General helper variables
load("helper_vars");
// Defines which page to use. Such as Home, Add, Edit, and List
load("check_login");
// Creates the html for quick links
load("page_def");
// Creates the text at the top af the screen i.e. 'Logged in as User (Log Out)'
load("quick_links");
// Defines the various field types
require("types.php");
load("plugins_type");

$content .= <<<PHP
if (\$is_zero_included) return;
PHP;

// The various pages
require("pages.php");
load("plugins_page");
// Creates the html for the nav tabs
load("nav_tabs");
// Creates the HTML for displaying warnings
load("render_warnings");
// Renders the page
load("render_page");

// Output the result
echo $content;
